name: VaultX
author: themrsung
version: '1.0.2'
main: com.themrsung.mc.VaultX
api-version: '1.21'
dependencies:
  bootstrap:
    Vault:
      required: false
  server:
    Vault:
      required: false
